# Based on https://evantay.com/blog/docusaurus-gh-action/ , Thank you @DigiPie
name: deploy-prod

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2
      - uses: actions/setup-node@e434342e4e324065b1b19b24586c710a1a68d2d7 #v2
        with:
          node-version: "12"
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@db4476a01402e1a7ce05f41832040eef16d14925 #v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
